### ISSUE TITLE
server error for one UI frame in gnome-contacts

### ISSUE THREAD

**Issue by dasj19** [Malizor/deckard#12]
Please check: https://deckard.malizor.org/?module=gnome-contacts&ui=data/ui/contacts-contact-form.ui&locale=ro_RO&display=1
The server returns 502 Bad Gateway

**Comment by Malizor** [comment]
Thanks for the report.
It turns out the UI you reported had really nothing interesting that Deckard could display.
This particular UI will be removed automatically from Deckard shortly.
However I did other changes that should hopefully fix other 502 errors on more useful UIs.
