### ISSUE TITLE
Add dconf-editor

### ISSUE THREAD

**Issue by josephgbr** [Malizor/deckard#2]
Newly added to translate-able list of software, dconf-editor has some .ui files. Can you please verify if it can be added to deckard and, if yes, make it available?

https://git.gnome.org/browse/dconf-editor/

**Comment by Malizor** [comment]
Thank you for your bug report.

There is not much to display in the .ui files of dconf-editor, but I added the module nevertheless.
You can see it here: http://deckard.malizor.org/?module=dconf-editor

Cheers!
