### ISSUE TITLE
Please add gd locale

### ISSUE THREAD

**Issue by gunchleoc** [Malizor/deckard#3]
Thanks for this great tool :)

Could you please add gd to the locale list? That would be a great time saver for me.

In case you need a country code, use gd_GB. Native language name is Gàidhlig.

**Comment by Malizor** [comment]
Thanks for the report. I will try to have a look later today.

**Comment by Malizor** [comment]
Scottish Gaelic is now available on https://deckard.malizor.org.

**Comment by gunchleoc** [comment]
Brilliant, thanks!
